services:
  app:
    build: .
    ports:
      - "3000:3000"
  
  ngrok:
    image: ngrok/ngrok:latest
    command: http app:3000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}
    depends_on:
      - app
    ports:
      - "4040:4040"